### PR TITLE
Splitting port from the remote address 

### PR DESCRIPTION
**Pull request by Abramovic**
Remote Address goes from "127.0.0.1:8000" to "127.0.0.1"

### CODE REVIEW

**Comment by zenazn** [comment]
Neither the `X-Forwarded-For` header nor the `X-Real-IP` header should have ports in them. Could you elaborate on why you think this patch is needed?

**Comment by Abramovic** [comment]
Right, ```X-Forwarded-For``` and ```X-Real-IP``` shouldn't have ports in them. This is if those headers are not present (ie: where the app isn't behind a load balancer) so this parses the original ```req.RemoteAddr``` which might include ports. 

If the ```X-Forwarded-For``` and ```X-Real-IP``` headers are present then ```req.RemoteAddr``` won't get parsed (line 45 and line 47).

**Comment by zenazn** [comment]
Err, `RemoteAddr` is set by `net/http`, and this middleware doesn't touch `RemoteAddr` unless one of those two headers is set. Are you perhaps printing out the port of `RemoteAddr` when you don't intend to?

**Comment by zenazn** [comment]
I don't think this is a bug in Goji so I'm going to close this PR. Please feel free to update this PR if you're still having issues!

**Pull request closed without merging**
