### PR TITLE
Added Replace middleware method and test case

### PR DESCRIPTION
**Pull request by jeevatkm**
Hello Carl - kindly have a look and let me know your thoughts for accepting this PR.

Cheers - Jeeva

### CODE REVIEW

**Comment by zenazn** [comment]
Is there any reason you couldn't accomplish the same effect with an `Insert(a, b)` followed by `Abandon(b)`?

**Comment by jeevatkm** [comment]
It is okay to use your mentioned approach, right now I'm using like that. I had a look on source code and thought it's better to have replace method for given middleware.

Then Added replace method and test case for that.

**Comment by zenazn** [comment]
I'd like to keep the API surface area minimal and orthogonal. Does `Replace` scratch a big need of yours (and if so, what need), or is it just a convenience over the two-line `Insert` and `Abandon` approach?

**Comment by jeevatkm** [comment]
I have requirement to apply set of middleware(s) for user request based on subscription (and few other criteria) to the sub-routes. So I have default middleware chain and few based on subscriptions.

Currently to achieve replace middleware via `Insert` and `Abandon` method takes round trip. It finds middleware position, appends, and does the shift in the stack. 
```go
i := m.findLayer(before)
...
m.appendLayer(middleware)
inserted := m.stack[len(m.stack)-1]
copy(m.stack[i+1:], m.stack[i:])
m.stack[i] = inserted
```
Instead we can find a position and replace with given middleware in that position.

```go
i := m.findLayer(existing)
...
m.stack[i] = *ml
```
As you mentioned, in this approach we also get convenience (however this is not my main goal). If you see improvements in the PR code, feel free to apply and accept this PR.

**Comment by zenazn** [comment]
Is the performance of manipulating middleware stacks important to your application? I wrote the code in question under the assumption that there would at most be tens of layers of middleware, and that performance was unlikely to be a concern here, but I'm happy to revisit that assumption if you're running into it.

**Comment by jeevatkm** [comment]
Yes, it is important. Having said that, application is not yet pushed to production and not yet tested under load. Will let you know after that.

**Comment by zenazn** [comment]
Since it's possible to replace middleware using `Insert` and `Abandon`, I don't think it's worth changing Goji's public API for this. Thanks for proposing this patch and chatting with me about it, though!

**Pull request closed without merging**
